version: '3.7'

services:
  url-shortener:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        PORT: ${PORT}
    container_name: url-shortener
    ports:
      - "8085:${PORT}"
    networks:
      - shortnet
    env_file: .env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: url-shortener-db
    ports:
      - "27017:27017"
    networks:
      - shortnet
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGODB_URI: ${MONGODB_URI}
    env_file: .env

  redis:
    image: redis:7.2.4-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    networks:
      - shortnet
    environment:
      REDIS_ADDRESS: ${REDIS_ADDRESS}
    env_file: .env

networks:
  shortnet: